version : '3.9'

# Creates a service made of :
# - 2 containers (flask, nginx)
# - 1 default network associated to the service 

services :

    flask :
        build : ./flask
        container_name : flask
        ports :
            - 5000:5000

    nginx :
        build : ./nginx
        container_name : nginx
        ports : 
            - 80:80

    prometheus :
        image : prom/prometheus:v2.26.0
        container_name : prometheus
        ports : 
            - 9090:9090
        volumes :
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    cadvisor :
        image : gcr.io/cadvisor/cadvisor:v0.39.0
        container_name : cadvisor
        user : root
        volumes :
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        ports :
          - 8080:8080

    grafana :
        image : grafana/grafana:7.5.4
        container_name : grafana
        volumes :
          - grafana-storage:/var/lib/grafana
        ports :
          - "3000:3000"

volumes:
    grafana-storage: